name: Feedback
description: Share your thoughts about the site
title: "Feedback: "
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      description: What should we improve or add?
      placeholder: Type your feedback here...
    validations:
      required: true
